### ISSUE TITLE
Request: Usage example of will topic and payload

### ISSUE THREAD

**Issue by agri-code** [mlesniew/PicoMQTT#10]
Hello there!

I've been impressed so far with what picoMQTT can do. However, I were unable to get it to send the will topic and payload.

Could you please provide a working example?

**Comment by agri-code** [comment]
I forgot to mention: I am using PicoMQTT::Client to connect to mosquitto with a will topic and payload. It is unclear to me after reading the code in what order to call `.connect(const char * host, uint16_t port, const char * id, const char * user, const char * pass, const char * will_topic, const char * will_message, const size_t will_message_length, uint8_t will_qos, bool will_retain, const bool clean_session, ConnectReturnCode * connect_return_code)`

and then `.begin()` or just connect and omit `.begin()` altogether and have it `.loop()` in the main function.

**Comment by agri-code** [comment]
Yeah, that's the thing... I absolutely suck at C/C++ and have a chronic lack of time to dig into anything deeper than very shallow waters these days. I'd appreciate it if you could make time to implement this and, if humanely possible, a the QOS level 2

I'll make it worth your time

**Comment by mlesniew** [comment]
Will messages for clients are implemented in the latest release, there's an example in the readme.   

I don't plan adding support for QoS level 2 for now.  This would require the messages to be stored in RAM until they're full confirmed as received by the broker.  This would complicate the code significantly and increase memory usage.
