### ISSUE TITLE
Compile-Error with PICOMQTT_DEBUG

### ISSUE THREAD

**Issue by MCSE-2000** [mlesniew/PicoMQTT#16]
I have enabled debug (PICOMQTT_DEBUG) and now I get the following errors:
/mnt/..../libraries/PicoMQTT/src/PicoMQTT/incoming_packet.cpp:70:19: error: #if with no expression
   70 | #if PICOMQTT_DEBUG
      |                   ^
/mnt/..../libraries/PicoMQTT/src/PicoMQTT/incoming_packet.cpp:81:19: error: #if with no expression
   81 | #if PICOMQTT_DEBUG
      |                   ^
/mnt/.../libraries/PicoMQTT/src/PicoMQTT/incoming_packet.cpp:97:19: error: #if with no expression
   97 | #if PICOMQTT_DEBUG
      |                   ^

But after the correction from #if PICOMQTT_DEBUG to #ifdef PICOMQTT_DEBUG no DEBUG information comes.

My problem was that the client did not work.
I took 2 ESP-01, one with basic_server.ino (static IP 192.168.2.40) and one with basic_client.ino (static IP 192.168.2.41).
I only got the following messages:
Publishing message in topic 'picomqtt/esp-E8:68:E7:80:0A:03': Hello #1
Publishing message in topic 'picomqtt/esp-E8:68:E7:80:0A:03': Hello #2
Publishing message in topic 'picomqtt/esp-E8:68:E7:80:0A:03': Hello #3
...

No answer Received message from server.

UPDATE 01.10.2023:
The client is working now. The ESP-01S has a defect. The ESP-01S client did not respond to a PING. But in the FritzBox it was displayed ONLINE and the WiFi.status was WL_CONNECTED. Another ESP-01 with the MAC E8:68:E7... did not work either. With an old ESP-01 now also the client works. But DEBUG info I still do not get.

**Comment by mlesniew** [comment]
Define PICOMQTT_DEBUG to 1.

pt., 29 wrz 2023, 20:32 użytkownik MCSE-2000 ***@***.***>
napisał:

**Comment by MCSE-2000** [comment]
Okay, thank you
