### ISSUE TITLE
Not a single example working? 

### ISSUE THREAD

**Issue by JFRosado** [mlesniew/PicoMQTT#3]
This looks like a nice library, if a single example worked. But none seems to work. Tryed both esp8266 and esp32 and allways get errors:

D:\Documents\Arduino\libraries\PicoMQTT\src\PicoMQTT\connection.cpp: In member function 'virtual void PicoMQTT::Connection::on_timeout()':
D:\Documents\Arduino\libraries\PicoMQTT\src\PicoMQTT\connection.cpp:32:12: error: 'class PicoMQTT::ClientWrapper' has no member named 'abort'
     client.abort();

In file included from D:\Documents\Arduino\libraries\PicoMQTT\src/PicoMQTT/connection.h:9:0,
                 from D:\Documents\Arduino\libraries\PicoMQTT\src/PicoMQTT/client.h:5,
                 from D:\Documents\Arduino\libraries\PicoMQTT\src/PicoMQTT.h:3,
                 from D:\Documents\Arduino\libraries\PicoMQTT\examples\server_local_pubsub\server_local_pubsub.ino:1:
D:\Documents\Arduino\libraries\PicoMQTT\src/PicoMQTT/outgoing_packet.h:39:22: error: 'virtual void PicoMQTT::OutgoingPacket::flush()' marked 'override', but does not override
         virtual void flush() override;
                      ^

**Comment by mlesniew** [comment]
All examples compile fine in the CI.

Please make sure that you're using the latest version (0.3.1).  Version 0.3.0 did not compile on Windows.

Also, make sure that you have a recent version of the board core installed.  In case of ESP8266 you need version Arduino core 3.1 or later.

**Comment by JFRosado** [comment]
Hi:
    Using the latest version (0.3.1). Updated core of esp8266 and it compiles. 
   
   ESP32 is latest and still no go:

In file included from D:\Documents\Arduino\libraries\PicoMQTT\src/PicoMQTT/connection.h:9:0,
                 from D:\Documents\Arduino\libraries\PicoMQTT\src/PicoMQTT/client.h:5,
                 from D:\Documents\Arduino\libraries\PicoMQTT\src/PicoMQTT.h:3,
                 from D:\Documents\Arduino\libraries\PicoMQTT\examples\server_local_pubsub\server_local_pubsub.ino:1:
D:\Documents\Arduino\libraries\PicoMQTT\src/PicoMQTT/outgoing_packet.h:39:22: error: 'virtual void PicoMQTT::OutgoingPacket::flush()' marked 'override', but does not override
         virtual void flush() override;
                      ^

**Comment by mlesniew** [comment]
What is the exact ESP32 core version that you have installed?

**Comment by JFRosado** [comment]
Version 1.0.6

**Comment by mlesniew** [comment]
The latest version is 2.0.7, see https://github.com/espressif/arduino-esp32/releases.  Please try upgrading.

**Comment by mlesniew** [comment]
I released version 0.3.2 now, which should produce a clear error message if the library is used with an older core.
