### ISSUE TITLE
Using w5500 instead of WiFi

### ISSUE THREAD

**Issue by jbr007** [mlesniew/PicoMQTT#30]

**Comment by mlesniew** [comment]
Sorry for the late reply -- currently the library only supports connections over wifi, but I hope to extend it soon.

**Comment by jbr007** [comment]
Hi Michael,

Many thanks for the feedback and your work.

Med vänliga hälsningar / Best regards

Jan Brandberg

Sent from my mobile

5 apr. 2024 kl. 19:10 skrev Michał Leśniewski ***@***.***>:

﻿

Sorry for the late reply -- currently the library only supports connections over wifi, but I hope to extend it soon.

**Comment by mlesniew** [comment]
Ethernet clients and brokers should now work, check out https://github.com/mlesniew/PicoMQTT/tree/master/examples/w5500_server and https://github.com/mlesniew/PicoMQTT/tree/master/examples/w5500_client.

Let me know if it works for you.

Note that to use this, you'll need to install the library from git directly.  The latest required changes are not released yet.

**Comment by jbr007** [comment]
Many thanks Michal,

Will test as soon as possible and let you know.

**Comment by mlesniew** [comment]
Hey @jbr007, did you have a chance to try out the Ethernet support?

**Comment by jbr007** [comment]
Hi Michael,

Thanks for your email. Yes, actually I downloaded it yesterday  on a ESP32 S3 now and it seems to work initially. I have only taken your demo code and use the client, not the broker yet.

Best regards

Jan Brandberg
+46733357505

Från: Michał Leśniewski ***@***.***>
Svara till: mlesniew/PicoMQTT ***@***.***>
Datum: fredag 7 juni 2024 18:03
Till: mlesniew/PicoMQTT ***@***.***>
Kopia: Jan Brandberg ***@***.***>, Mention ***@***.***>
Ämne: Re: [mlesniew/PicoMQTT] Using w5500 instead of WiFi (Issue #30)


Hey @jbr007<https://github.com/jbr007>, did you have a chance to try out the Ethernet support?

**Comment by mlesniew** [comment]
Hey Jan, any updates on this?  

Do you think we can close this ticket now?

**Comment by jbr007** [comment]
Hi,

Yes

Med vänliga hälsningar / Best regards

Jan Brandberg

Sent from my mobile

7 juli 2024 kl. 20:39 skrev Michał Leśniewski ***@***.***>:

﻿

Hey Jan, any updates on this?

Do you think we can close this ticket now?

**Comment by DriekdeGadgetfreak** [comment]
W5500 has only 8 sockets. Can you limit the number of sockets the mqtt server uses?
