### ISSUE TITLE
disconnected_callback

### ISSUE THREAD

**Issue by mhaberler** [mlesniew/PicoMQTT#33]
https://github.com/mlesniew/PicoMQTT/blob/fd106140553f60c8a356992db112ec5ada25abf9/src/PicoMQTT/client.cpp#L284 

this probably should be ` disconnected_callback();`

**Comment by mlesniew** [comment]
Oh of course! 

Are you able to fix it and submit a PR?  If not, I can fix it in the evening.

**Comment by mhaberler** [comment]
> Am 08.05.2024 um 08:07 schrieb Michał Leśniewski ***@***.***>:
> 
> 
> Oh of course!
> Are you able to fix it and submit a PR? If not, I can fix it in the evening.

will do

MagicSettings works nicely, creating an example

**Comment by mlesniew** [comment]
#35 is now merged.  Thank you!
