### ISSUE TITLE
Websocket disconnects

### ISSUE THREAD

**Issue by mhaberler** [mlesniew/PicoMQTT#36]
I cant quite make sense of this, and where this belongs

Setup: [MQTT Explorer](https://github.com/thomasnordquist/MQTT-Explorer) master commit  65b86a 
built with:
```
yarn
yarn build
yarn start
```
PicoMQTT is 172.16.0.159, commit 460c258 on an ESP32-S3
PicoWebsockets commit 42092f
MQTT Explorer is 172.16.0.191

Traffic ca maybe 30-50 publishes/sec, memory not an issue (> 190kB free heap)

PicoMQTT console logs:
```
[612870][D][NetworkClient.cpp:568] connected(): Disconnected: RES: 0, ERR: 128
[616862][D][NetworkClient.cpp:568] connected(): Disconnected: RES: 0, ERR: 128
```
also:
```
IncomingPacket read incorrect number of bytes: 0/2
IncomingPacket read incorrect number of bytes: 0/2
```
MQTT Explorer console log:
```
RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear
    at Receiver.getInfo (/Users/mah/Ballon/src/BalloonWare/networking/MQTT-Explorer/node_modules/ws/lib/receiver.js:171:14)
    at Receiver.startLoop (/Users/mah/Ballon/src/BalloonWare/networking/MQTT-Explorer/node_modules/ws/lib/receiver.js:131:22)
    at Receiver._write (/Users/mah/Ballon/src/BalloonWare/networking/MQTT-Explorer/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:447:12)
    at _write (node:internal/streams/writable:389:10)
    at Writable.write (node:internal/streams/writable:393:10)
    at Socket.socketOnData (/Users/mah/Ballon/src/BalloonWare/networking/MQTT-Explorer/node_modules/ws/lib/websocket.js:1162:35)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9) {
  code: 'WS_ERR_UNEXPECTED_RSV_2_3',
  [Symbol(status-code)]: 1002
}
```
Pcap: https://static.mah.priv.at/cors/pcap/mqttws-explorer.pcapng

NB from packet 774 onwards strange things happen:

![ ](https://github.com/mlesniew/PicoMQTT/assets/901479/ca180a90-cb59-4275-a83b-37c05415cdb4)

**Comment by mhaberler** [comment]
I also tried MQTTX, very similar symptom: https://static.mah.priv.at/cors/pcap/mqttx.pcapng packet 697

**Comment by mlesniew** [comment]
Thanks for raising this.  It could actually be a bug in PicoWebsocket, but it might be hard to reproduce without PicoMQTT.

It looks like in packet 776 in the first capture file there's a websocket frame with invalid length.  The Websocket frame length is set to 100 bytes, but data seems to continue beyond that.  

The client expects another websocket frame header after the first 100 bytes, but it receives payload data, which can't be decoded.

So this could mean that the bug is related to how the payload length is encoded.  I can look into that. 

If you're using ESP32, can you check if publishes are always fired from the same core/thread/task as the one which calls the `loop()` method?   I'm asking because the payload data looks like measurements captured via BLE.   Depending on how this is implemented, the BLE advertisement callbacks on the ESP32 can be called from the 2nd core.  This can easily lead to problems like the ones we're observing here, because PicoMQTT and PicoWebsocket are not reentrant.

**Comment by mhaberler** [comment]
re ESP32: no, that cant be it

the BLE ads are [passed into a ringbuffer](https://github.com/mhaberler/picomqtt-tests/blob/cores3-prod/src/scanner.cpp#L283-L299) (probably on core0) which are [read and decoded](https://github.com/mhaberler/picomqtt-tests/blob/cores3-prod/src/scanner.cpp#L317-L322), then published from the main loop() which is core1

**Comment by mhaberler** [comment]
the payload for packed 776 was [published here](https://github.com/mhaberler/picomqtt-tests/blob/07ac1f2ac9d51040e0beadff8781dd7c6a892b75/src/ublox.cpp#L86-L88)

**Comment by mhaberler** [comment]
oh, now that you say it I smell something..  stop the presses ;)

the second level interrupt handler is a FreeRTOS thread, and is not bound to a core
it also calls the GPS polling code

so it might well be the case what you're suspicing

let me tack that thread to core1 or move the GPS polling code to loop() one way or the other

**Comment by mhaberler** [comment]
moved that code to be called by loop() and no, pretty sure this was not the cause

the error reappears with other publishes 

interestingly a similar issue arises when using MQTT-over-TCP with the same code

see this pcap https://static.mah.priv.at/cors/pcap/tcp.pcapng packet 710 onwards

<img width="1476" alt="image" src="https://github.com/mlesniew/PicoMQTT/assets/901479/fd303dd9-9c96-4647-bac3-f6109a6bb846">

**Comment by mhaberler** [comment]
I guess this excludes the Websockets code for now

**Comment by mhaberler** [comment]
well this is strange.. I switched to the PicoSettings begin/live scheme which activates settings subscriptions later in the startup process, and gets around the chicken-and-egg problem https://github.com/mhaberler/PicoSettings/issues/1

and I cannot observe the errors reported above any more, no more disconnects

MQTTX, MQTT Explorer and a web client connected, turned up reporting rates.. nothing

will let run over night and check in the morning

all that changed is - the Settings subscribes and publishes happen later in the setup phase

**Comment by mlesniew** [comment]
You closed before I could send more tips...  Here are a few thoughts:
* There is no need to set up PicoMQTT subscriptions after calling `begin()`.  Subscriptions can actually be added at any time.  The only place where they shouldn't be changed is when one of the callbacks is currently running (so within the  callbacks themselves).  I understand that delaying the subscriptions until after the call to `begin()` seemed to fix the problem, but I think it's just a coincidence.
* You're saying that in your setup there's a ring buffer that the cores use to communicate.  Are you sure that ring buffer itself is thread safe? 
* I've created a new branch `mutexes`. It introduces basic thread-safety.   A mutex is locked in `loop()` and when any publish is in progress.  Give it a try and see what happens.  If PicoMQTT is actually used from multiple threads and we're missing it, this might magically fix it or cause a deadlock.   
* If you're using PicoSettings, you should make `PicoSettings:SettingsBase` non-copyable and non-copy constructible (defined [here](https://github.com/mhaberler/PicoSettings/blob/master/src/PicoSettings.h#L102).  The subscription callbacks of its subclasses capture `this`, which can be pointing to the wrong place after such operations.  Unsubscribing in the destructor is also a good idea.  This is probably unrelated, but still worth fixing.

**Comment by mhaberler** [comment]
thanks!
 I'll go through the callbacks just to make sure

re ringbuffer: I use the [ESP-IDF ringbuffer](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/system/freertos_additions.html), for instance [here](https://github.com/mhaberler/picomqtt-tests/blob/cores3-prod/src/measurements.cpp#L113-L126) and [here](https://github.com/mhaberler/picomqtt-tests/blob/cores3-prod/src/icm20948.cpp#L40-L52) - very nice zero-copy scheme and robust, never given me troubles

`mutexes` branch - thanks, will give it a try. The timer task and the BLE task are always suspicious

PicoSettings - will give it a stab

**Comment by mhaberler** [comment]
in case someone else has this problem: I had a second such case due to optimistic coding..

I tried the `mutexes` branch and it immediately deadlocked at [the lock in begin_publish()](https://github.com/mlesniew/PicoMQTT/blob/mutexes/src/PicoMQTT/server.cpp#L348-L350) 

very easy to find in the debugger and fix - recommended

**Comment by mhaberler** [comment]
a plea for help: I am unable to fix this, either `master` or `mutexes` branch - and I've used  every tool in my box

I took pains to make sure only loopTask will call mqtt.* methods
I'm using Arduino 3.0.1 with libraries lifted from Tasmota but that seems to have no discernible impact


the symptoms:

- plain MQTT-over-TCP works reliable
- running over PicoWebsockets produces the  'WS_ERR_UNEXPECTED_RSV_2_3',  status code  1002 error every few seconds, any client
- connection resets but recovers due to client reconnecting

here's a [pcap](https://static.mah.priv.at/cors/pcap/websockets-disconnect.pcapng) 

not sure what to do; running short on time for a demo :-/

the current status is [here](https://github.com/mhaberler/picomqtt-tests/tree/find-hang)  - it might be too convoluted to build

I can try a pared-down example to reproduce if you're stuck

**Comment by mhaberler** [comment]
I might have looked like an idiot above, but I finally got it working on any ESP32-S3 and C3 device. 

It was a most unlikely cause: the [M5Unified/M5GFX support library](https://github.com/m5stack/M5Unified). 

The symptoms above only show when M5Unified is in play - it works perfectly if one runs using "pure Arduino".

I have no idea yet what the causality is.

**Comment by mlesniew** [comment]
No worries, great that we know what component caused it.  

Do you still need help with this?

**Comment by mhaberler** [comment]
no,  I do not thinks so - we can close for now and reopen if something surfaces

thanks!

**Comment by mlesniew** [comment]
Sure, no problem
