### ISSUE TITLE
websocket Client

### ISSUE THREAD

**Issue by KartikDevarde2601** [mlesniew/PicoMQTT#42]
i need Help ! ...As per the example code, I created a WebSocket server. It is working fine with the Android app, but I didn't understand how another client, like another ESP, can connect to the WebSocket broker. i try basic client example to publish message and subscribe from android app it not working

**Comment by mlesniew** [comment]
Can you share the exact code of the broker and the client code you're running?

**Comment by KartikDevarde2601** [comment]
websocket broker example  code if working with android app.. [https://github.com/mlesniew/PicoMQTT/blob/master/examples/websocket_server/websocket_server.ino](url)

In client basic client example 
[https://github.com/mlesniew/PicoMQTT/blob/master/examples/basic_client/basic_client.ino](url) client work well when both broker and client on TCP protocol . but i not getting any example of WebSocket client  i try just change the port too 1883 to 8080 but it not working can you pls share WebSocket client example

**Comment by mlesniew** [comment]
Ah I see what you mean now.

Try updating the client code to define `mqtt` like this:
```
// Define the client -- any Arduino Client subclass can be
// used here (e.g. EthernetClient)
WiFiClient client;

// Define the websocket
PicoWebsocket::Client websocket(client);

// Define the MQTT client
PicoMQTT::Client mqtt(websocket, "<broker address>", <broker port>);
```

**Comment by KartikDevarde2601** [comment]
thank you so much it working ... client is connected with broker using WebSocket
