### ISSUE TITLE
Not an issue; just another option for String wildcard_value = mqtt.get_topic_element(topic, 1);

### ISSUE THREAD

**Issue by rin67630** [mlesniew/PicoMQTT#45]
Hi Michal,

just to mention: I was successful self-consuming MQTT messages and extracting values with the additional library JsonDocument:
```
mqtt.subscribe("#", [](const char* topic, const char* message) {
JsonDocument doc;
      auto error = deserializeJson(doc, message);
      if (not error) {
        Total = doc["ENERGY"]["Total"];
        Yesterday = doc["ENERGY"]["Yesterday"];
        Today = doc["ENERGY"]["Today"];
        // ...
        Current = doc["ENERGY"]["Current"];
        Temperature = doc["ANALOG"]["Temperature"];
      }
```
Used directly in the setup() subscription, which is a powerful, flexible and nice way to extract values by name.

 Enjoy!

**Comment by mlesniew** [comment]
Hey, great it works for you, but I really struggle to understand how your approach is different from the typical usage...

Your snippet seems to be the same as the [example from the readme](https://github.com/mlesniew/PicoMQTT?tab=readme-ov-file#json) and the [arduinojson.ino example sketch](https://github.com/mlesniew/PicoMQTT/blob/master/examples/arduinojson/arduinojson.ino)...

**Comment by rin67630** [comment]
Oh yes, sorry.
I had overseen your given example and "reinvented the wheel".

I was just referring to your method 
mqtt.get_topic_element(); 
which appear to be the simple way to do basic MQTT querries.
