### ISSUE TITLE
error - connected_callback

### ISSUE THREAD

**Issue by asbs-eng** [mlesniew/PicoMQTT#49]
#include <WiFi.h>
#include <PicoMQTT.h>
#include <Wire.h> 

const char* ssid = "TP-Link_7C96"; 
const char* password = "94546729"; 

IPAddress local_ip(10,80,113,100); 
IPAddress gateway(10,80,113,0);
IPAddress subnet(255,255,255,0);

const char broker[] = "10.80.113.50";
int        port     = 1883;
PicoMQTT::Client mqtt(broker);   

void setup() {
  Serial.begin(115200);
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  WiFi.config(local_ip, gateway, subnet);
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(1000);
  }
  Serial.print("connected !");

  mqtt.connected_callback = [] {
    Serial.println("mqtt connected");
  }
  mqtt.begin();
}

void loop() {
  mqtt.loop();
}

why do I get an error  at mqtt.begin();  -> expected ';' before mqtt  ?

Regards

**Comment by ehabtawfikelbwab** [comment]
There is missing `;`

Change to:
```
 mqtt.connected_callback = [] {
    Serial.println("mqtt connected");
 };
```

**Comment by mlesniew** [comment]
Yep, @ehabtawfikelbwab is right -- it's just a syntax error, not related to the library.
