### ISSUE TITLE
Ethernet library support

### ISSUE THREAD

**Issue by lukaszt-pcs** [mlesniew/PicoMQTT#5]
Hi, congrats! Your library works brilliantly over wifi.
I wonder if there is an easy implementation possible for the ethernet module. e.g. w5500wisnet. please advise.

**Comment by mlesniew** [comment]
Hey, thanks, great that it works for you too.

Although I wrote it mainly with WiFi in mind, adding support for Ethernet should be possible and relatively easy.  Currently the library relies internally on the WiFiClient and WiFiServer server classes.  Ethernet libs provide equivalent classes -- EthernetClient and EthernetServer with the same API.  

The most elegant solution would be to convert the classes in PicoMQTT to templates.  There can be some additional tweaks needed, but this way it would be easiest to work with W5500 library and potentially other libraries too.
