### ISSUE TITLE
slow response when connection is lost

### ISSUE THREAD

**Issue by asbs-eng** [mlesniew/PicoMQTT#52]
The program can detect when the connection is disconnected or connected. It's just that when the connection is connected, the response from the switch when pressed is fast, whereas when the connection is disconnected, the response from the switch is sometimes detected, sometimes not. How can the response from the switch be stable, especially when the connection is lost?

regards

#include <WiFi.h>
#include <PicoMQTT.h>
#include <pt.h>
#include <Wire.h> 
#include <TimeLib.h>

int LED_BUILTIN = 2;
int cnt = 0;

const char* ssid = "TP-Link_7C96"; 
const char* password = "94546729"; 

IPAddress local_ip(10,80,113,100); //dev 1
IPAddress gateway(10,80,113,0);
IPAddress subnet(255,255,255,0);

const char broker[] = "10.80.113.50";
int        port     = 1883;
int reconnect_interval = 2500;
int keep_alive         = 1000;
int socket_timeout     = 2500;

bool con_sts = false;    //status 1 connected 0 disconnected
bool con_save = false;   //save 1 save data to dtbs

PicoMQTT::Client mqtt(broker,port,"dev_id01",nullptr,nullptr,reconnect_interval,keep_alive,socket_timeout);   

const int btn_disp = 35; 
const int btn_sub = 34;  
const int btn_fr = 33;  
int btn_disp_old = 0;
int btn_sub_old = 0;
int btn_fr_old = 0;
int btn_state = 0;

static struct pt pt1;   //blink
static struct pt pt3;   //sw

static int protothreadBlinkLED(struct pt *pt)
{
  static unsigned long lastTimeBlink = 0;
  char buf[6];
  PT_BEGIN(pt);
  while(1) {
    lastTimeBlink = millis();
    PT_WAIT_UNTIL(pt, millis() - lastTimeBlink > 250);
    digitalWrite(LED_BUILTIN, HIGH);
    lastTimeBlink = millis();
    PT_WAIT_UNTIL(pt, millis() - lastTimeBlink > 250);
    digitalWrite(LED_BUILTIN, LOW);  
  }
  PT_END(pt);
}

static int protothreadSw(struct pt *pt)
{
  static unsigned long lastTimeBlink = 0;
  String strcnt;
  PT_BEGIN(pt);
  while(1) {
    lastTimeBlink = millis();
    btn_state = digitalRead(btn_disp);
    if (btn_state != btn_disp_old) {
      btn_disp_old = btn_state;
      if (btn_state == HIGH) {
        Serial.println("button display HIGH");
        strcnt = "btn cnt "+String(cnt);
        pub_send("qc/btn1",strcnt);
        cnt = cnt + 1;
        if (cnt>100) {
          cnt = 0;
        }
      } 
    }
    PT_WAIT_UNTIL(pt, millis() - lastTimeBlink > 100);
  }
  PT_END(pt);
}

void setup() {
  Serial.begin(115200);
  Wire.begin();
  delay(1000);  
  pinMode(LED_BUILTIN, OUTPUT);
  pinMode(btn_disp, INPUT);
  pinMode(btn_sub, INPUT);
  pinMode(btn_fr, INPUT);  
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  WiFi.config(local_ip, gateway, subnet);
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(1000);
  }
  Serial.println("connected !");

  mqtt.connected_callback = [] {
    con_sts = true;
    Serial.println("mqtt connected");
    if (con_save == true) {
      dtbs_resend();  //resend dtbs -> mqtt
    }
  };
  
  mqtt.disconnected_callback = [] {
    Serial.println("mqtt disconnected");
    con_sts = false;   
  };
  mqtt.begin();
  con_sts = true;
  con_save = false;  

  PT_INIT(&pt1);  //blink led
  PT_INIT(&pt3);  //cek input sw
}

void loop() {
  mqtt.loop();
  protothreadBlinkLED(&pt1);
  protothreadSw(&pt3);
  delay(10);
}

void pub_send(String topic,String payload) {
  bool cekcek;
  Serial.println("pub send !!!");
  if (con_sts == true) {
    cekcek = mqtt.publish(topic,payload,0,false,1);    
    //save data when disconnect
    if (cekcek == false) {
      con_sts = false; 
      dtbs_save();
      con_save = true;
    }
  } else {
     //save data when disconnect 
     dtbs_save();
     con_save = true;
  }  
}

void dtbs_save() {
  Serial.println("SAVE DATABASE");  
}

void dtbs_resend() {
  Serial.println("RESEND DATABASE");
  con_save = false;
}

**Comment by mlesniew** [comment]
Hey @asbs-eng -- the library can block sometimes, especially when the connection is lost.  This was discussed in another issue before, please have a look at this comment: https://github.com/mlesniew/PicoMQTT/issues/48#issuecomment-2498404456

**Comment by justbendev** [comment]
If you have more than one core like the ESP32 you can dedicate a core for time sensitive tasks that are non blocking.

Example : A light switch using esp32 can dedicate one core for all communications (WiFi , MQTT) and the other core just reading inputs and basic logic.
