### ISSUE TITLE
Debug options

### ISSUE THREAD

**Issue by JohnCallingham** [mlesniew/PicoMQTT#6]
Hi
Great library. Is there any way to add debug info?
Thanks
John

**Comment by mlesniew** [comment]
This can be done using preprocessor defines.

Build the library with `PICOMQTT_DEBUG` defined to get some extra diagnostic messages printed to the serial.  

Build the library with `PICOMQTT_DEBUG_TRACE_FUNCTIONS` defined to make the library print (almost) all internal function calls and returns to the serial.  Note that this is very verbose and will slow things down significantly, but it's very useful for debugging the library itself. 

You can enable these options by adding a compiler flag or un-commenting one of the lines here:
https://github.com/mlesniew/PicoMQTT/blob/master/src/PicoMQTT/config.h#L23

**Comment by JohnCallingham** [comment]
Many thanks
