### ISSUE TITLE
Implementation for TLS

### ISSUE THREAD

**Issue by dasflaigsi** [mlesniew/PicoMQTT#8]
Is there a plan for implementing TLS in near future?

**Comment by mlesniew** [comment]
So far I was not planning to implement TLS support, but I think it could be implemented relatively easily.

Internally, the MQTT broker classes use the `WiFiClient` class as an interface for all communication.  The ESP8266 and ESP32 cores also have a `WiFiClientSecure` class implementation, which has the same interface with additional TLS functionality.

My first thought on how to implement this would be by using C++ templates.  This would potentially allow us to not only use TLS, but perhaps also other types of connections, e.g. Ethernet.

If you would like to give it a try, I'm happy to review your PR and help where I can.

**Comment by stuzenz** [comment]
Congratulations on the project. It looks quite nice. 

The README.md is great too by the way, just a thought though, it might be a nice addition to add into the README.md on whether TLS and async is supported. 

I am looking out for a library now that covers TLS, non-blocking (async I guess), and covers QOS1. I suspect there are quite a few people who start with pubsubclient and then start looking for a replacement when they notice how much the reconnects can cause blocking on the processor.

Again, congrats - brilliant job, I will come back again for another project of mine.

**Comment by justbendev** [comment]
@stuzenz TLS is already supported.

**Comment by stuzenz** [comment]
I don't know how I missed. Many thanks I will check the library again. Thanks for the quick response!
